import React from 'react';
import { ProductId } from '../../../types';
import { DebriefDataset } from '../../../hooks/useDebriefData';
import { SlideFrame } from '../components/SlideFrame';
import { TeamBarChart } from '../components/TeamBarChart';
import { formatDebriefCurrency } from '../../../utils/debriefFormat';

interface SlideProps {
  productId: ProductId;
  productName: string;
  dataset: DebriefDataset;
  revealStep: number;
  currentSlide: number;
  totalSlides: number;
}

export const ProductRevenueSlide: React.FC<SlideProps> = ({
  productId,
  productName,
  dataset,
  revealStep,
  currentSlide,
  totalSlides
}) => {
  const chartData = dataset.teams.map(t => ({
    name: t.name,
    value: t.record.revenue.byProduct[productId] || 0,
    colorIndex: t.colorIndex
  }));

  return (
    <SlideFrame
      title={`Revenue: ${productName}`}
      eyebrow={`${productName} Product Performance`}
      footer={`Total revenue generated by ${productName} for each competing team`}
      currentSlide={currentSlide}
      totalSlides={totalSlides}
      teams={dataset.teams}
    >
      <TeamBarChart
        data={chartData}
        formatter={(v) => formatDebriefCurrency(v, true, false)}
        height={650}
        startFromZero={false}
      />
    </SlideFrame>
  );
};
