import React from 'react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend
} from 'recharts';
import { DebriefDataset } from '../../../hooks/useDebriefData';
import { SlideFrame, PRODUCT_COLORS } from '../components/SlideFrame';
import { formatDebriefCurrency } from '../../../utils/debriefFormat';

interface SlideProps {
  dataset: DebriefDataset;
  revealStep: number;
  currentSlide: number;
  totalSlides: number;
}

export const RevenueByProductSlide: React.FC<SlideProps> = ({ dataset, revealStep, currentSlide, totalSlides }) => {
  const chartData = dataset.teams.map(t => ({
    name: t.name,
    TechBook: t.record.revenue.byProduct.techbook || 0,
    Zroid: t.record.revenue.byProduct.zroid || 0,
    iTab: t.record.revenue.byProduct.itab || 0
  }));

  return (
    <SlideFrame
      title="Revenue per Product by Team"
      eyebrow="Product Portfolio"
      footer="Comparison of revenue generated by TechBook, Zroid, and iTab across all active teams"
      currentSlide={currentSlide}
      totalSlides={totalSlides}
      teams={dataset.teams}
    >
      <div className="w-full bg-[#131C2E] border border-[#22304A] rounded-2xl p-8 shadow-2xl">
        <ResponsiveContainer width="100%" height={520}>
          <BarChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 10 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#22304A" vertical={false} />
            <XAxis dataKey="name" stroke="#8296B4" tick={{ fill: '#E8EDF7', fontSize: 22, fontWeight: 600 }} tickLine={false} />
            <YAxis stroke="#8296B4" tick={{ fill: '#8296B4', fontSize: 18 }} tickFormatter={(v) => formatDebriefCurrency(v, true)} tickLine={false} axisLine={false} />
            <Tooltip
              contentStyle={{ backgroundColor: '#0B1220', borderColor: '#22304A', borderRadius: '8px', color: '#E8EDF7', fontSize: '18px', fontFamily: 'IBM Plex Mono' }}
              formatter={(val: any) => [formatDebriefCurrency(Number(val)), '']}
            />
            <Legend wrapperStyle={{ paddingTop: '20px', fontSize: '20px', fontWeight: 'bold' }} />
            <Bar dataKey="TechBook" fill={PRODUCT_COLORS.techbook} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
            <Bar dataKey="Zroid" fill={PRODUCT_COLORS.zroid} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
            <Bar dataKey="iTab" fill={PRODUCT_COLORS.itab} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </SlideFrame>
  );
};
