import React from 'react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend
} from 'recharts';
import { DebriefDataset } from '../../../hooks/useDebriefData';
import { SlideFrame, PRODUCT_COLORS } from '../components/SlideFrame';
import { CustomAxisTick } from '../components/CustomAxisTick';
import { formatDebriefCurrency } from '../../../utils/debriefFormat';

interface SlideProps {
  dataset: DebriefDataset;
  revealStep: number;
  currentSlide: number;
  totalSlides: number;
}

export const RevenueByProductSlide: React.FC<SlideProps> = ({ dataset, currentSlide, totalSlides }) => {
  const chartData = dataset.teams.map(t => ({
    name: t.name,
    TechBook: t.perf?.revenueByProduct?.techbook ?? 0,
    Zroid: t.perf?.revenueByProduct?.zroid ?? 0,
    iTab: t.perf?.revenueByProduct?.itab ?? 0
  }));

  return (
    <SlideFrame
      title="Revenue per Product by Team"
      eyebrow="Product Portfolio"
      footer="Comparison of revenue generated by TechBook, Zroid, and iTab across all active teams"
      currentSlide={currentSlide}
      totalSlides={totalSlides}
      teams={dataset.teams}
    >
      <div className="w-full h-full flex-1 min-h-0 bg-white border border-slate-200 rounded-2xl p-6 shadow-xl flex flex-col justify-center">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData} margin={{ top: 25, right: 30, left: 30, bottom: 65 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" vertical={false} />
            <XAxis dataKey="name" stroke="#64748B" interval={0} tick={<CustomAxisTick fontSize={16} maxCharsPerLine={13} />} tickLine={false} />
            <YAxis stroke="#64748B" tick={{ fill: '#64748B', fontSize: 18, fontWeight: 600 }} tickFormatter={(v) => formatDebriefCurrency(v, true, false)} tickLine={false} axisLine={false} />
            <Tooltip
              contentStyle={{ backgroundColor: '#0F172A', borderColor: '#1E293B', borderRadius: '12px', color: '#F8FAFC', fontSize: '18px', fontFamily: 'IBM Plex Mono' }}
              formatter={(val: any) => [formatDebriefCurrency(Number(val), true, true), '']}
            />
            <Legend wrapperStyle={{ paddingTop: '35px', fontSize: '20px', fontWeight: 'bold', color: '#0F172A' }} />
            <Bar dataKey="TechBook" fill={PRODUCT_COLORS.techbook} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
            <Bar dataKey="Zroid" fill={PRODUCT_COLORS.zroid} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
            <Bar dataKey="iTab" fill={PRODUCT_COLORS.itab} radius={[6, 6, 0, 0]} isAnimationActive={true} animationDuration={700} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </SlideFrame>
  );
};
